bsc.df<-read.csv("Agreement Sales Jan 17 2020  214PM.csv",stringsAsFactors = FALSE)
names(bsc.df)
library(skimr)
skim(bsc.df)
str(bsc.df)
my.bsc.df<-bsc.df[,c(7,10,15)]
droplevels(my.bsc.df$Sale.Type,exclude=c("New","Rejoin"))
library(tidyverse)
new.df<-filter(my.bsc.df,Sale.Type!="Rewrite")
new.df<-filter(my.bsc.df,Sale.Type=="Rewrite")
new.df<-filter(my.bsc.df,Sale.Type!="Rewrite")
new.df<-filter(my.bsc.df,Agreement!="Ambassador Program Invoiced")
View(new.df)
new.df<-filter(my.bsc.df,Agreement!="Employee Agreement")
new.df<-filter(new.df,Sale.Type!="Rewrite")
new.df<-filter(new.df,Agreement!="Ambassador Program Invoiced")
new.df<-filter(new.df,Sale.Type!="Rewrite")
new.df<-filter(new.df,Agreement!="Employee Agreement")
new.df<-filter(new.df,Agreement!="Guest Agreement")
new.df<-filter(new.df,Agreement!="First-Class Agreement")
new.df<-filter(new.df,Agreement!="Guest Agreement Online Only")
new.df<-filter(new.df,Agreement!="Locker Rental")
new.df<-filter(new.df,Agreement!="Passport Conversions 45 Day Cxl")
new.df<-filter(new.df,Agreement!="Passport Conversions")
new.df<-filter(new.df,Agreement!="Personal Training 1 Pack")
new.df<-filter(new.df,Agreement!="Personal Training 2 Pack")
new.df<-filter(new.df,Agreement!="Personal Training 4 Pack")
new.df<-filter(new.df,Agreement!="Personal Training 8 Pack")
new.df<-filter(new.df,Agreement!="Personal Training 12 Pack")
new.df<-filter(new.df,Agreement!="Personal Training 24 Pack")
new.df<-filter(new.df,Agreement!="Personal Training Memberships 4 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Memberships 8 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership 4 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership 8 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership 12 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership Elite 12 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership Elite 4 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership Elite 8 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership 1 Session")
new.df<-filter(new.df,Agreement!="Personal Training Membership 1 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership 2 Sessions")
new.df<-filter(new.df,Agreement!="Personal Training Membership 2 Session")
new.df<-filter(new.df,Agreement!="Personal Training Membership 1 Session")
new.df<-filter(new.df,Agreement!="Personal Training Membership 4 Sessions 6 Mth")
new.df<-filter(new.df,Agreement!="Personal Training Membership 8 Sessions 6 Mth")
new.df<-filter(new.df,Agreement!="Personal Training Membership 8 Sessions 6 Mth")
new.df<-filter(new.df,Agreement!="Personal Training Elite 4 Pack")
new.df<-filter(new.df,Agreement!="Personal Training Membership Elite 1 Session")
new.df<-filter(new.df,Agreement!="Premier Babysitting")
new.df<-filter(new.df,Agreement!="Premier Conversions")
new.df<-filter(new.df,Agreement!="Premier Conversions 45 Day Cxl")
new.df<-filter(new.df,Agreement!="PTM 4 Sessions $100.00 Off 1st Month")
new.df<-filter(new.df,Agreement!="PTM 8 Sessions $200.00 Off 1st Month")
new.df<-filter(new.df,Agreement!="PTM 12 Sessions $200.00 Off 1st Month")
new.df<-filter(new.df,Agreement!="PTM Elite 12 Sessions $200.00 Off 1st Month")
new.df<-filter(new.df,Agreement!="PTM Elite 4 Sessions $100.00 Off 1st Month")
new.df<-filter(new.df,Agreement!="Regional Passport Conversions")
new.df[,4]<-months
names(new.df)[names(new.df) == "V4"] <- "Months"
month.names<-c("1"="January","2"="February","3"="March",
                                 "4"="April","5"="May","6"="June","7"="July",
                                 "8"="August","9"="September","10"="October",
                                 "11"="November","12"="December")
new.df$Months<-as.character(month.names[new.df$Months])
daily.sales<-as.data.frame(table(new.df$Sale.Date))
months.ds<-month(as.POSIXlt(daily.sales$Var1, format="%m/%d/%Y"))
head(months.ds,200)
daily.sales[3]<-months.ds
names(daily.sales)[names(daily.sales) == "V3"] <- "Months"
daily.sales$Months<-as.character(month.names[daily.sales$Months])
plot(daily.sales)
dat<-read.csv("Sales Data Months Counts.csv",header = FALSE)
dat$V1<-sort(dat$V1,decreasing=TRUE)
plot(dat,type="h")
library(lattice)
barchart(V2|V1,data=dat)
